
# LookupDNS defines the actual DNS address to keep eye on.
lookupEndpoint: www.example.com
# expectedIp specifies the value to look for in DNS query response on <LookupDNS>.
expectedCname: "specific.exmaple.org"
# kubeconfig is the path to a kubeconfig file.
kubeconfig: "~/.kube/config"
#LogLevel is the level/severity for the logs. Must be one of [info,debug,error].
logLevel: 4
#Server defines the configuration of the HTTP server.
server: 
  bindAddress: "localhost"
  port: 8080